server:
  port: 8090
#spring:
#  cloud:
#    gateway:
#      routes:
#      - id: beego
#        uri: http://localhost:8080
#        predicates:
#        - Path=/beego/**
#        filters:
#        - StripPrefix=1
#      - id: webgo
#        uri: http://localhost:9090
#        predicates:
#        - Path=/webgo/**
#        filters:
#        - StripPrefix=1