spring:
  application:
    name: demo2
#  sleuth:
#    sampler:
#      probability: 1.0
#  zipkin:
#    base-url: http://localhost:9411/
server:
  port: 8082
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka